// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY_i2qXyPI1Gv3V3KcYDYGMmKe-D364dk',
    appId: '1:991639478812:web:7a1e1cbbe1d0d9bf0fb5d9',
    messagingSenderId: '991639478812',
    projectId: 'accoletting',
    authDomain: 'accoletting.firebaseapp.com',
    storageBucket: 'accoletting.appspot.com',
    measurementId: 'G-X0SS58002V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRjjaE_sYsrZj5LZw3nW8hSB1yvZR-cw',
    appId: '1:991639478812:android:a410b0c6724fdfba0fb5d9',
    messagingSenderId: '991639478812',
    projectId: 'accoletting',
    storageBucket: 'accoletting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB7Vzvg__sEsIp3AKJbClo7OtQoZY4zhc',
    appId: '1:991639478812:ios:982604bf214a48700fb5d9',
    messagingSenderId: '991639478812',
    projectId: 'accoletting',
    storageBucket: 'accoletting.appspot.com',
    iosBundleId: 'com.example.listviewApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB7Vzvg__sEsIp3AKJbClo7OtQoZY4zhc',
    appId: '1:991639478812:ios:edeeacf9a711a8110fb5d9',
    messagingSenderId: '991639478812',
    projectId: 'accoletting',
    storageBucket: 'accoletting.appspot.com',
    iosBundleId: 'com.example.listviewApplication.RunnerTests',
  );
}
